export const NavData2 = {
    "সর্বশেষ":{
        "link":"/latest-news",
        "name":"সর্বশেষ",
        "icon":"latest",
        "popup":false
    },
    "নির্বাচন":{
        "link":"/election-news",
        "name":"নির্বাচন",
        "icon":"election",
        "popup":false
    },
    "জাতীয়":{
        "link":"/national-news",
        "name":"জাতীয়",
        "icon":"national",
        "popup":false
    },
    "রাজনীতি":{
        "link":"/politics",
        "name":"আর্কাইভ",
        "icon":"রাজনীতি",
        "popup":false
    },
    "সারাদেশ":{
        "link":"/country-news",
        "name":"সারাদেশ",
        "icon":"country",
        "popup":false
    },
    "বিশ্ব":{
        "link":"/world-news",
        "name":"বিশ্ব",
        "icon":"world",
        "popup":false
    },
    "খেলা":{
        "link":"/sports",
        "name":"খেলা",
        "icon":"sports",
        "popup":false
    },
    "শিক্ষা":{
        "link":"/education-news",
        "name":"শিক্ষা",
        "icon":"education",
        "popup":false
    },
    "বাণিজ্য":{
        "link":"/business-news",
        "name":"বাণিজ্য",
        "icon":"business",
        "popup":false
    },
    "বিনোদন":{
        "link":"/entertainment",
        "name":"বিনোদন",
        "icon":"entertainment",
        "popup":false
    },
    "ভিডিও":{
        "link":"/video",
        "name":"ভিডিও",
        "icon":"video",
        "popup":false
    },
}