import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const solaimanLipi = localFont({
  src: "../../public/SolaimanLipi/SolaimanLipi.ttf", // or .ttf
  variable: "--font-bangla",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="bn">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${solaimanLipi.className} antialiased leading-none`}
      >
        <Navbar />
        <div className="mt-3 max-w-[1500px] mx-auto">
          {children}
        </div>
        <Footer></Footer>
      </body>
    </html>
  );
}
